### ISSUE TITLE
Google AdsBot and Mediapartners-Google

### ISSUE THREAD

**Issue by Jonathanofzo** [mbaersch/simple-bot-detector#1]
Hi,

I love your variable template. Could you add the following two bots that visit websites quite often that use Google Ads and/or AdSense?

"AdsBot"
"Mediapartners-Google"

Source: https://developers.google.com/search/docs/advanced/crawling/overview-google-crawlers

**Comment by mbaersch** [comment]
this is odd - I have a database that tracks all visits of those two mentioned as "Ads Bot" going back 5+ years but I somehow managed to forget to include them here. Thanks for the hint, I will update the code ASAP and add a few more.

But: It may be the case that you never see any effect of this change because I am quite sure that both do not render a page and so they should have no effect on client-side request generation for your endpoint.
